### ISSUE TITLE
ReferenceError: CircularDependencyPlugin is not defined

### ISSUE THREAD

**Issue by Diarsid** [aackerman/circular-dependency-plugin#10]
Hi!
I cannot get your plugin working :(
I installed plugin via

> npm install --save-dev circular-dependency-plugin

My config:
```
var webpack = require('webpack');

module.exports = {
    entry: "./src/main.js",
    output : {
        path: "./dist.env.prod",
        filename: "bundle.js"
    },
    module: {
        loaders: [{
            test: /\.js$/,
            exclude: /node_modules/,
            loaders: ['babel-loader']
        }]
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env':{
                'NODE_ENV': JSON.stringify('production')
            }
        }),
        new CircularDependencyPlugin({
            // exclude detection of files based on a RegExp
            // exclude: /a\.js/,
            // add errors to webpack instead of warnings
            failOnError: true
        })
    ]
};
```
Trying to pack it, i got following message:
```
E:\1__projects\webstorm\react.js\beam.server.ui\webpack.config.env.prod.js:22
        new CircularDependencyPlugin({
            ^

ReferenceError: CircularDependencyPlugin is not defined
    at Object.<anonymous> (E:\1__projects\webstorm\react.js\beam.server.ui\webpack.config.env.prod.js:22:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (E:\2__LIB\NPM_global\npm\node_modules\webpack\bin\convert-argv.js:30:13)
    at Object.<anonymous> (E:\2__LIB\NPM_global\npm\node_modules\webpack\bin\webpack.js:56:40)
    at Module._compile (module.js:413:34)
```
I'm not proficient in JS, so I could make a mistake somewhere in configuration, but I don't see it. Please, correct me, or fix this issue.
Thanks.

**Comment by Diarsid** [comment]
Sorry! It is my stupid mistake, I've forgotten to require plugin. Stupid mistake.
One more sorry.
