### ISSUE TITLE
DeprecationWarning: The `util._extend` API is deprecated

### ISSUE THREAD

**Issue by dennisat** [aackerman/circular-dependency-plugin#101]
Error
```
(node:78938) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
    at new CircularDependencyPlugin (/Users/dennisat/dev/x-company/x-project/node_modules/.pnpm/circular-dependency-plugin@5.2.2_webpack@4.47.0_webpack-cli@3.3.12_/node_modules/circular-dependency-plugin/index.js:8:20)
    at Object.<anonymous> (/Users/dennisat/dev/x-company/x-project/packages/mhc-ui-components/webpack.plugins.js:9:5)
...
```

This because the 

`let extend = require('util')._extend`

Is deprecated.

**Can you fix it please?**

**Comment by gpoitch** [comment]
https://github.com/aackerman/circular-dependency-plugin/pull/100

**Comment by andrewplummer** [comment]
Would love to see this fixed as well. I quite like this plugin.

**Comment by fregante** [comment]
The project here is abandoned. I published @gpoitch's patch under a new name and added the types from `@types/circular-dependency-plugin`

This is not a maintained fork, it just solves this single issue until this package is maintained again, if ever.

```sh
npm rm circular-dependency-plugin @types/circular-dependency-plugin
npm install @fregante/circular-dependency-plugin --save-dev
```

And then replace your imports

```diff
- import CircularDependencyPlugin from "circular-dependency-plugin";
+ import CircularDependencyPlugin from "@fregante/circular-dependency-plugin";
```

**Comment by ross-acuity** [comment]
Thank you very much, @fregante. For anyone finding his solution and passing by, I'll add that, for me, the package is only a dev dependency. Install as appropriate for you.

**Comment by fregante** [comment]
Oh right, I updated the commands to save as dev dependency.

**Comment by dakota-kallas** [comment]
I'd recommend using [patch-package](https://www.npmjs.com/package/patch-package) for this if you don't want to install a fork.

Here is my `.patch` file for the fix:
```
diff --git a/node_modules/circular-dependency-plugin/index.js b/node_modules/circular-dependency-plugin/index.js
index 32c7be9..3b126a2 100644
--- a/node_modules/circular-dependency-plugin/index.js
+++ b/node_modules/circular-dependency-plugin/index.js
@@ -1,18 +1,18 @@
 let path = require('path')
-let extend = require('util')._extend
 let BASE_ERROR = 'Circular dependency detected:\r\n'
 let PluginTitle = 'CircularDependencyPlugin'
 
 class CircularDependencyPlugin {
   constructor(options) {
-    this.options = extend({
+    this.options = {
       exclude: new RegExp('$^'),
       include: new RegExp('.*'),
       failOnError: false,
       allowAsyncCycles: false,
       onDetected: false,
-      cwd: process.cwd()
-    }, options)
+      cwd: process.cwd(),
+      ...options
+    }
   }
 
   apply(compiler) {
```
