### ISSUE TITLE
Error: "Path must be a string.". Doesn't work with DllReferencePlugin

### ISSUE THREAD

**Issue by zlk89** [aackerman/circular-dependency-plugin#35]
Getting error when using with `DllReferencePlugin`:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1227:5)
    at CircularDependencyPlugin.isCyclic (/node_modules/circular-dependency-plugin/index.js:92:18)
```

Tried to log the `depModule` which doesn't have resource:

```
DelegatedModule {
  dependencies:
   [ DelegatedSourceDependency {
       module: [Object],
       weak: false,
       optional: false,
       loc: undefined,
       request: 'dll-reference vendor_a41f543bb658b494f9b0',
       userRequest: 'dll-reference vendor_a41f543bb658b494f9b0',
       __NormalModuleFactoryCache: [Object] },
     DelegatedExportsDependency {
       module: null,
       weak: false,
       optional: false,
       loc: undefined,
       originModule: [Circular],
       exports: true } ],
  blocks: [],
  variables: [],
  type: 'require',
  context: null,
  debugId: 2261,
  hash: undefined,
  renderedHash: undefined,
  resolveOptions: {},
  factoryMeta: {},
  warnings: [],
  errors: [],
  buildMeta: { providedExports: true },
  buildInfo: {},
  reasons:
   [ ModuleReason {
       module: [Object],
       dependency: [Object],
       explanation: undefined,
       _chunks: null }],
  _chunks:
   SortableSet { ... },
  id: null,
  index: 1191,
  index2: 1181,
  depth: 5,
  issuer:
   NormalModule {
     dependencies:
      [ [Object]],
     blocks: [],
     variables: [],
     type: 'javascript/auto',
     context: '/Users/xxx/node_modules/xxx',
     debugId: 3876,
     hash: undefined,
     renderedHash: undefined,
     resolveOptions: {},
     factoryMeta: {},
     warnings: [],
     errors: [],
     buildMeta: { providedExports: true },
     buildInfo:
      { cacheable: true,
        fileDependencies: [Object],
        contextDependencies: Set {},
        strict: true },
     reasons: [ [Object], [Object] ],
     _chunks:
      SortableSet {
        [Object],
        _sortFn: [Function: sortById],
        _lastActiveSortFn: null,
        _cache: undefined,
        _cacheOrderIndependent: undefined },
     id: null,
     index: 1213,
     index2: 1246,
     depth: 6,
     issuer:
      NormalModule { ...l },
     profile: undefined,
     prefetched: false,
     built: true,
     used: null,
     usedExports: null,
     optimizationBailout: [],
     _rewriteChunkInReasons: undefined,
     useSourceMap: true,
     request: '/Users/xxx/node_modules/xxx/xxx.js',
     userRequest: '/Users/xxx/node_modules/xxx/xxx.js',
     rawRequest: './xxx',
     binary: false,
     parser:
      Parser {
        _pluginCompat: [Object],
        hooks: [Object],
        options: {},
        sourceType: 'auto',
        scope: undefined,
        state: undefined,
        comments: undefined },
     generator: JavascriptGenerator {},
     resource: '/Users/xxx/xxx/node_modules/xxx/xxx.js',
     loaders: [],
     error: null,
     _source:
      OriginalSource {
        _value: '.....code',
        _name: 'xxx.js' },
     buildTimestamp: 1523397148514,
     _cachedSource: undefined,
     _cachedSourceHash: undefined,
     lineToLine: false,
     _lastSuccessfulBuildMeta: { providedExports: true },
     _ast: null },
  profile: undefined,
  prefetched: false,
  built: true,
  used: null,
  usedExports: null,
  optimizationBailout: [],
  _rewriteChunkInReasons: undefined,
  useSourceMap: true,
  sourceRequest: 'dll-reference vendor_a41f543bb658b494f9b0',
  request: './node_modules/lodash/isNil.js',
  userRequest: './node_modules/lodash/isNil.js',
  originalRequest:
   NormalModule {...},
  delegateData:
   { id: './node_modules/lodash/isNil.js',
     buildMeta: { providedExports: true } } }
```

Dependencies:
```
  "dependencies": {
    "add-asset-html-webpack-plugin": "^2.1.3",
    "autodll-webpack-plugin": "^0.3.9",
    "autoprefixer": "^8.2.0",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^8.0.0-beta.2",
    "babel-plugin-import": "^1.7.0",
    "circular-dependency-plugin": "^5.0.1",
    "compression-webpack-plugin": "^1.1.11",
    "css-loader": "^0.28.11",
    "eslint-plugin-babel": "^5.0.0",
    "eslint-plugin-promise": "^3.7.0",
    "file-loader": "^1.1.11",
    "font-loader": "^0.1.2",
    "happypack": "^5.0.0-beta.3",
    "html-webpack-plugin": "^3.2.0",
    "lodash": "^4.17.5",
    "null-loader": "^0.1.1",
    "postcss-loader": "^2.1.3",
    "preload-image-loader": "^1.0.0",
    "react-hot-loader": "^4.0.1",
    "resolve-url-loader": "^2.3.0",
    "sass-loader": "^6.0.7",
    "stats-webpack-plugin": "^0.6.2",
    "style-loader": "^0.20.3",
    "uglifyjs-webpack-plugin": "^1.2.4",
    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.14"
  }
```

webpack plugins:
```
  new webpack.DllReferencePlugin({
    context: basePath,
    manifest:path.join(dllFolder, 'vendor.manifest.json'),
  }),
  new HtmlWebpackPlugin(),
  new AddAssetHtmlPlugin({
    filepath: path.resolve(dllFolder, './*.dll.js'),
  }),
  new CircularDependencyPlugin({
    cwd: basePath,
    exclude: /node_modules/,
    failOnError: false,
  }),
```

And I found a workaround which fixes this issue:
Using different webpack object for `DllReferencePlugin`, i.e., something like this
```
const webpack2 = require('another-webpack-node-module-path')
webpack2.DllReferencePlugin()
```

**Comment by aackerman** [comment]
I believe this is fixed in `5.0.2`.
