### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by binarykitchen** [aackerman/circular-dependency-plugin#4]
```
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:8:11)
  at Object.posix.relative (path.js:496:3)
  at /home/michael-heuberger/Development/smx3-frontend/node_modules/circular-dependency-plugin/index.js:42:41
  at Array.forEach (native)
...
```

**Comment by aackerman** [comment]
Can you do some simple debugging for this and `console.log` the values passed to `path.relative`

Adjust the code in your node_modules to look something like this.

```js
if (isCyclic(module) && !plugin.options.exclude.test(module.resource)) {
    console.log(process.cwd(), module.resource, module);
    var relativePathToModule = path.relative(process.cwd(), module.resource);
    console.warn(relativePathToModule, 'contains cyclical dependency');
}
```
Otherwise I'm not sure why those values would be undefined.

**Comment by binarykitchen** [comment]
sorry, can't help now ... leave this ticket open for later or someone else helps

**Comment by jeremejevs** [comment]
Same issue for me, getting the following:

```
/app undefined DependenciesBlock {
  dependencies: *snip*,
  blocks: [],
  variables: [],
  context: '/app/node_modules/moment/locale',
  reasons: [ ModuleReason { module: [Object], dependency: [Object] } ],
  debugId: 2909,
  lastId: -1,
  id: 978,
  index: 978,
  index2: 1069,
  chunks: 
   [ Chunk {
       id: 0,
       ids: [Object],
       name: 'main',
       modules: [Object],
       chunks: [],
       parents: [],
       blocks: [],
       origins: [Object],
       files: [Object],
       rendered: true,
       entry: true,
       initial: true,
       hash: *snip*,
       renderedHash: *snip* } ],
  warnings: [],
  dependenciesWarnings: [],
  errors: [],
  dependenciesErrors: [],
  resolveDependencies: [Function: bound resolveDependencies],
  recursive: true,
  regExp: /^\.\/.*$/,
  addon: '',
  cacheable: true,
  contextDependencies: [ '/app/node_modules/moment/locale' ],
  built: true,
  issuer: '/app/node_modules/moment/moment.js',
  optional: true,
  useSourceMap: true,
  building: undefined,
  builtTime: *snip* }
```

And then it throws `Path must be a string. Received undefined`.
