### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by kruglay** [aackerman/circular-dependency-plugin#42]
Hi!
I tried circular-dependency-plugin 4 and 5 version and get the same error.

package.json:

```
{
  "name": "mvs-dash",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/core": "7.2.0",
    "@nivo/bar": "^0.52.1",
    "@nivo/line": "^0.52.1",
    "@nivo/pie": "^0.52.1",
    "@svgr/webpack": "4.1.0",
    "ag-grid-community": "^19.1.4",
    "ag-grid-enterprise": "^19.1.4",
    "ag-grid-react": "^19.1.2",
    "antd": "^3.13.6",
    "apollo-boost": "^0.1.28",
    "apollo-link-context": "^1.0.17",
    "axios": "^0.18.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "^24.5.0",
    "babel-loader": "8.0.4",
    "babel-plugin-named-asset-import": "^0.2.2",
    "babel-polyfill": "^6.26.0",
    "babel-preset-react-app": "^6.1.0",
    "base-64": "^0.1.0",
    "base64-img": "^1.0.4",
    "bfj": "6.1.1",
    "build-url": "^1.3.2",
    "case-sensitive-paths-webpack-plugin": "2.1.2",
    "chalk": "2.4.1",
    "circular-dependency-plugin": "^4.0.0",
    "cors": "^2.8.5",
    "css-loader": "1.0.1",
    "dotenv": "6.2.0",
    "dotenv-expand": "4.2.0",
    "draft-js": "^0.10.5",
    "draftjs-to-html": "^0.8.4",
    "eslint": "5.9.0",
    "eslint-config-react-app": "^3.0.8",
    "eslint-loader": "2.1.1",
    "eslint-plugin-flowtype": "3.2.0",
    "eslint-plugin-import": "2.14.0",
    "eslint-plugin-jsx-a11y": "6.1.2",
    "eslint-plugin-react": "7.11.1",
    "file-loader": "2.0.0",
    "fork-ts-checker-webpack-plugin-alt": "^0.4.14",
    "fs-extra": "7.0.1",
    "geodist": "^0.2.1",
    "graphql": "^14.1.1",
    "graphql-tag": "^2.10.1",
    "html-to-draftjs": "^1.4.0",
    "html-webpack-plugin": "4.0.0-alpha.2",
    "identity-obj-proxy": "3.0.0",
    "jest": "^24.5.0",
    "jest-pnp-resolver": "1.0.2",
    "jest-resolve": "23.6.0",
    "jwt-decode": "^2.2.0",
    "konva": "^3.2.3",
    "leaflet": "^1.4.0",
    "lodash": "^4.17.11",
    "mini-css-extract-plugin": "0.4.5",
    "minio": "^7.0.5",
    "moment": "^2.24.0",
    "nivo": "^0.31.0",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "pnp-webpack-plugin": "1.2.1",
    "postcss-flexbugs-fixes": "4.1.0",
    "postcss-loader": "3.0.0",
    "postcss-preset-env": "6.4.0",
    "postcss-safe-parser": "4.0.1",
    "prop-types": "^15.7.2",
    "quill": "^1.3.6",
    "randomcolor": "^0.5.4",
    "react": "^16.8.3",
    "react-apollo": "2.5.2",
    "react-app-polyfill": "^0.1.3",
    "react-beautiful-dnd": "^10.1.0",
    "react-blocks": "^1.1.4",
    "react-dev-utils": "^6.0.4",
    "react-dom": "^16.8.3",
    "react-draft-wysiwyg": "^1.13.2",
    "react-dropzone": "^9.0.0",
    "react-icons": "^3.5.0",
    "react-image": "^1.5.1",
    "react-image-gallery": "^0.8.14",
    "react-intl": "^2.8.0",
    "react-konva": "^16.8.6",
    "react-leaflet": "^2.2.1",
    "react-localization": "^1.0.13",
    "react-native-base64": "0.0.2",
    "react-panelgroup": "^1.0.7",
    "react-quill": "^1.3.3",
    "react-router-dom": "^4.3.1",
    "react-split-pane": "^0.1.85",
    "react-table": "^6.9.2",
    "react-text-ellipsis": "^1.5.2",
    "react-vis": "^1.11.6",
    "recharts": "^1.5.0",
    "recharts-color-utils": "^0.1.1",
    "resolve": "1.8.1",
    "seafile-js": "^0.2.68",
    "style-loader": "0.23.1",
    "terser-webpack-plugin": "1.1.0",
    "text-diff": "^1.0.1",
    "ts-react-json-table": "^0.1.1",
    "url-loader": "1.1.2",
    "webdav": "^2.6.0",
    "webpack": "4.27.1",
    "webpack-dev-server": "^3.2.1",
    "webpack-manifest-plugin": "2.0.4",
    "workbox-webpack-plugin": "3.6.3",
    "xlsx": "^0.14.1"
  },
  "scripts": {
    "start": "node $NODE_DEBUG_OPTION scripts/start.js",
    "build:prod": "node --max_old_space_size=4096 scripts/build.js",
    "build:dev": "REACT_APP_GQL_SERVER_DEV=1 node --max_old_space_size=4096 scripts/build.js",
    "test": "node scripts/test.js"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@types/minio": "^7.0.1",
    "node-sass": "^4.9.4",
    "sass-loader": "^7.1.0",
    "webpack-cli": "^3.2.3"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "resolver": "jest-pnp-resolver",
    "setupFiles": [
      "react-app-polyfill/jsdom"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx}"
    ],
    "testEnvironment": "jsdom",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$",
      "^.+\\.module\\.(css|sass|scss)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web",
      "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  }
}
```

here my webpack.config.dev.js:
```
new CircularDependencyPlugin({
        // exclude detection of files based on a RegExp
        exclude: /a\.js|node_modules/,
        // add errors to webpack instead of warnings
        failOnError: true,
        // set the current working directory for displaying module paths
        cwd: process.cwd(),
      }),
```

**Comment by aackerman** [comment]
Hi @kruglay can you please include you exact versions of the plugin, webpack, and if possible a stack trace. I can take a look at this later tonight.

**Comment by kruglay** [comment]
[Here](https://nimb.ws/sj4wp8) a screen with error
"circular-dependency-plugin": "5.0.2",
"webpack": "4.27.1",

stack trace from log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/kruglay/.nvm/versions/node/v10.11.0/bin/node',
1 verbose cli   '/home/kruglay/.nvm/versions/node/v10.11.0/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mvs-dash@0.1.0~prestart: mvs-dash@0.1.0
6 info lifecycle mvs-dash@0.1.0~start: mvs-dash@0.1.0
7 verbose lifecycle mvs-dash@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle mvs-dash@0.1.0~start: PATH: /home/kruglay/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kruglay/MVS/dash/node_modules/.bin:/home/kruglay/.nvm/versions/node/v10.11.0/bin:/home/kruglay/.local/share/umake/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle mvs-dash@0.1.0~start: CWD: /home/kruglay/MVS/dash
10 silly lifecycle mvs-dash@0.1.0~start: Args: [ '-c', 'node scripts/start.js' ]
11 silly lifecycle mvs-dash@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle mvs-dash@0.1.0~start: Failed to exec start script
13 verbose stack Error: mvs-dash@0.1.0 start: `node scripts/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/kruglay/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/kruglay/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid mvs-dash@0.1.0
15 verbose cwd /home/kruglay/MVS/dash
16 verbose Linux 4.18.0-20.2-liquorix-amd64
17 verbose argv "/home/kruglay/.nvm/versions/node/v10.11.0/bin/node" "/home/kruglay/.nvm/versions/node/v10.11.0/lib/node_modules/npm/bin/npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error mvs-dash@0.1.0 start: `node scripts/start.js`
22 error Exit status 1
23 error Failed at the mvs-dash@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by unlight** [comment]
```
+-- webpack@4.29.6
`-- webpack-dev-server@3.2.1
```
Error in version `circular-dependency-plugin@5.0.2` - Cannot read property 'tap' of undefined  
`circular-dependency-plugin@4.4.0` - DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

**Comment by aackerman** [comment]
@unlight do you have a stack trace you can include?

Version 5 of the plugin is expected to work with webpack >= 4.0.1 and I would expect that the warning `DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead` is not for this plugin because the `.hooks` syntax is being used. https://github.com/aackerman/circular-dependency-plugin/blob/master/index.js#L21-L22

**Comment by aackerman** [comment]
I was also able to test this with Node 10 and webpack 4.29.6 and I didn't run into any issues.

**Comment by unlight** [comment]
Sorry, my bad. I pasted plugin to wrong place.
After create-react-app eject, I got webpack.config 650+ lines, there several place with `plugins` section, resolve, modules, etc. I lost in debris.

Version 5.0.2 is working ok with webpack@4.29.6 (but not with webpack after react-scripts eject, because it launches webpack in subprocess - that's why is hard to provide stack trace)

**Comment by aackerman** [comment]
@unlight can you include your version of `create-react-app`? I'm seeing this working with the defaults for these versions.

create-react-app 3.0.1
circular-dependency-plugin 5.0.2
webpack 4.29.6

I essentially ran the following on macOS

```
brew upgrade yarn
yarn create react-app test && cd test
yarn run eject
yarn add circular-dependency-plugin
# edit webpack.config.js in config
# add `const CircularDependencyPlugin = require('circular-dependency-plugin')
# add `new CircularDependencyPlugin()` to the plugins section
yarn start
```

**Comment by unlight** [comment]
`create-react-app 3.0.0` Clean install works.
So, I do not have complains about plugin, it's my environment issue.

Thank you for great plugin.
