### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by Yangfan2016** [aackerman/circular-dependency-plugin#82]
```
TypeError: Cannot read property 'tap' of undefined
    at CircularDependencyPlugin.apply (/xxx/node_modules/circular-dependency-plugin/index.js:22:32)
    at /xxx/node_modules/webpack/node_modules/enhanced-resolve/lib/ResolverFactory.js:327:10
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (/xxx/node_modules/webpack/node_modules/enhanced-resolve/lib/ResolverFactory.js:326:10)
    at ResolverFactory._create (/xxx/node_modules/webpack/lib/ResolverFactory.js:57:28)
    at ResolverFactory.get (/xxx/node_modules/webpack/lib/ResolverFactory.js:49:28)
    at NormalModuleFactory.getResolver (/xxx/node_modules/webpack/lib/NormalModuleFactory.js:521:31)
    at /xxx/node_modules/webpack/lib/NormalModuleFactory.js:165:32
    at /xxx/node_modules/webpack/lib/NormalModuleFactory.js:129:4
    at handleExternal (/xxx/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:28:34)

```

```json
{
"circular-dependency-plugin": "^5.2.2",
"webpack": "^4.44.1",
}

```

**Comment by makarov-roman** [comment]
I've got the same error when I put this plugin to `config.resolve.plugins` instead of `config.plugins`
